### ISSUE TITLE
Proposal: Add shock tube species profiles as an experiment type

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/PyKED#60]
### PyKED/ChemKED version
v0.1.5

### Code sample
```
---
file-author:
    name: Carly LaGrotta
    ORCID:
file-version: 0
reference:
    doi: 10.1016/j.proci.2012.06.108
    authors:
        - name: Zekai Hong
          ORCID:
        - name: King Yiu Lam
          ORCID:
        - name: Ritobrata Sur
          ORCID:
        - name: Shengkai Wang
          ORCID:
        - name: David F. Davidson
          ORCID:
        - name: Ronald K. Hanson
          ORCID:
    journal: Proceedings of the Combustion Institute
    year: 2013
    volume: 34
    pages: 565-571
    detail: On the rate constants of OH+HO2 and HO2+HO2
experiment-type: Species profile
apparatus:
    kind: shock tube
    institution: Stanford University
    facility: stainless steel shock tube
    inner-diameter: &diam
        value: 15.2
        units: cm
common-properties:
    pressure: &pres
        - 1.672 atm
        - uncertainty-type: relative
          uncertainty: 0.02
    temperature: &temp
        - 1182 K
        - uncertainty-type: relative
          uncertainty: 0.01
    composition: &comp
      kind: mole-fraction
      species:
        - species-name: H2O2
          amount:
            - 0.002046 #can one specify it in ppm by giving ppm as units?
            - uncertainty-type: relative
              uncertainty: 0.05
        - species-name: H2O
          amount:
            - 0.001113
            - uncertainty-type: relative
              uncertainty: 0.05
        - species-name: O2
          amount:
            - 0.000556
            - uncertainty-type: relative
              uncertainty: 0.05
        - species-name: Ar
          amount:
            - 0.996285 #can balance be specified here instead of a value?
            - uncertainty-type: relative
              uncertainty: 0.05
    time-shift: &timeshift
      - 0 s
      - uncertainty-type: absolute
        uncertainty: 0.01 ms
    assumptions: &assumptions
        thermal-boundary: adiabatic #vs. isothermal
        mechanical-boundary: constant pressure #vs. constant volume
        equation-of-state: ideal gas
datapoints: #is it necessary to include the temperature: *temp stuff for each item even though it's common?
    - csvfile: 'hong_pci2013_oh.csv'
      targets:
        - name: OH
          type: mole fraction # vs. concentration or absorbance
          species: OH
          absolute-uncertainty: 1E-6
          relative-uncertainty: .05
    - csvfile: 'hong_pci2013_h2o.csv'
      targets:
        - name: H2O
          type: mole fraction
          species: H2O
          absolute-uncertanity: 1E-6
          relative-uncertainty: .05
    - csvfile: 'hong_pci2013_abs227nm.csv'
      targets:
        - name: 'abs_227nm'
          type: absorbance
          wavelength:
            value: 227
            units: nm
          absorbing_species:
            - species: H2O2
              cross-section:
                value: 1.40E+05
                units: 'cm^2 mol^-2'
                relative-uncertainty: .1
            - species: HO2
              cross-section:
                value: 1.27E+06
                units: 'cm^2 mol^-1'
                relative-uncertainty: .1
          path_length: *diam
          absolute-uncertainty: .01
```

Proposed by Mike Burke's group at Columbia

**Comment by kyleniemeyer** [comment]
To start, we don't need the `' '` around strings, like in the `csvfile` and `units` fields

**Comment by bryanwweber** [comment]
This is excellent! A few thoughts:

1) `ppm` is not really necessary as a unit, just use `E-06`
2) The `time-shift` field looks fine, but it should be specified in each datapoint
3) I'm not sure about the `assumptions` field. How often are each of the options used? What is the utility of providing this?
4) Yes, it is necessary to explicitly include each required option in a data point. Therefore, each data point needs a `temperature`, `composition`, and `pressure`. See https://github.com/pr-omethe-us/PyKED/issues/59 
5) Rather than having a csv file with the data, it would IMO be better to have 3 YAML files, one for each data set. That will reduce the problems YAML has dealing with tables. You can check out the RCM example for a case where a two-column table is used, https://github.com/pr-omethe-us/PyKED/blob/master/pyked/tests/testfile_rcm.yaml With that file in mind, I'd propose the following schema for a single target:
```
datapoints:
  - temperature: *temperature
    composition: *composition
    pressure: *pressure
    time-shift: *timeshift
    species-history:
      time:
        units: s
        column: 0
      target:
        name: OH  # This is more or less arbitrary, for user convenience
        type: 
          - mole fraction  # or concentration or absorbance, need a field for units of concentration
          - uncertainty-type: relative
            uncertainty: 0.1
        column: 1
      values:
        - ...
```
6) Absolute uncertainty and relative uncertainty are mutually exclusive, I think...
7) For absorbance, maybe something like this:
```
datapoints:
  - temperature: *temperature
    composition: *composition
    pressure: *pressure
    time-shift: *timeshift
    species-history:
      time:
        units: s
        column: 0
      target:
        name: abs_227nm  # This is more or less arbitrary, for user convenience
        type: 
          - absorbance
          - wavelength:
             - 227 nm
             - uncertainty-type: relative
                uncertainty: 0.1
          - path-length:
              - 0.1 m
              - uncertainty-type: relative
                uncertainty: 0.1
          - absorbing_species:
              - species-name: H2O2
                 cross-section:
                   - 0.1E5 cm2/mol
                   - uncertainty-type: relative
                      uncertainty: 0.1
              - species-name: OH
                 cross-section:
                   - 0.2E5 cm2/mol
                   - uncertainty-type: relative
                      uncertainty: 0.1
        column: 1
      values:
        - ...
```
8) I don't think the diameter should go in the apparatus field. We're trying to come up with an alternate file format for apparatuses, something that would store the details of each device and give it a unique identifier.

OK, lots to think about here!

**Comment by kyleniemeyer** [comment]
I agree that each file should only contain a single dataset or series—it's ok if there are multiple ChemKED files from a single paper, for example.

**Comment by kyleniemeyer** [comment]
Regarding assumptions, I am also wary of putting something specific to a way of modeling (at least I assume that's what that is for) in a file that is meant to encode the measurement itself.

That said, if this sort of information is similar to (e.g.) pre-ignition pressure rise in a shock tube, or compression volume trace or post-compression heat loss in an RCM, then I think it should be included.  However, I don't think that is the case.

**Comment by bryanwweber** [comment]
Email from Mike Burke to Bryan:

> Hi Bryan,
> 
> Thanks for your comments.  Some followups below to continue the dialogue...
> 
> 1 Good point, agreed.
> 
> 2,4 It might be worth pointing out there's one key aspect of this type of multi-species experiment that I suspect would to to differences in how one would treat it compared to a series of ignition delay times -- each of the species time profiles are measured in a single experiment rather than multiple experiments.  As a result, the time-shift (2), as well as the initial pressure, temperature, and composition (4) should be identical -- such that I would see value in listing them among common-properties only and not in the datapoints section because they would be redundant and because it would avoid someone making a mistake by entering different initial values for different datapoints.  
> 
> 3 Yeah, I'm not sure I even like the 'assumptions' field so much anyway -- I have the same philosophical objections to the assumptions block within our proposed shock tube file.  The tricky thing with this Hong experiment that we're emulating in this YAML file is that there is a driver insert in the shock tube such that the authors suggest that it is nearly constant pressure rather than the more conventional constant volume assumption used for shock tube (based on their pressure traces).  So in that regard, it is similar to the pressure trace that might in other experiments be used to model boundary layer effects or heat loss, or in the present case lack thereof.
> 
> 5 Similar to 2,4, all of the species time profiles correspond to a single experiment not just a single paper, and have all the same common properties like initial temperature, pressure, composition, etc.  In that case, does it still make sense to have 3 different YAML files to represent it?  My students initially suggested csv files such that tables with titles for each column could be viewed very easily and read in similarly easily using pandas dataframes.  In many species profile experiments, there could be tables consisting of many dozens of rows (i.e. species) rather than just a few.  Another advantage of this format would be that it is a very common way that people right now represent their data in supplemental material for papers.  Thoughts?
> 
> 6 I would see value in having both relative and absolute uncertainties for species time profiles for example, where one could account for "calibration" type uncertainties (which perhaps might be relative) and one could account for signal-to-noise/detection limit type uncertainties (which perhaps might be absolute).  At different points along the time profile, the relative uncertainties may take on different values on an absolute basis.
> 
> 8 Ah, I see.  I could see some value in doing that.  I suppose you're planning on having an apparatus YAML format which describes an apparatus that could be identified by name or tag only within the experiment YAML file.  I should mention that the shock tube diameter is a necessary component to predicting the absorption signal through a Beer's Law analysis.
> 
>

**Comment by bryanwweber** [comment]
Mike,

Thanks for the quick response! Some further clarifications:

> such that I would see value in listing them among common-properties only and not in the datapoints section because they would be redundant and because it would avoid someone making a mistake by entering different initial values for different datapoints.

Even values listed in the `common-properties` section still have to be entered into every data point, with the minor difference that they can be added by reference, for instance, the following is the preferred method:

```
common-properties:
  temperature: &temp
    - value
  pressure: &pres
    - value
datapoints:
  - temperature: *temp
    pressure: *pres
    ...
  - temperature: *temp
    pressure: *pres
    ...
```
This is an intentional design decision on our part. We felt there were two likely scenarios:
1) Properties in the `common-properties` block get autofilled for missing properties in each data point
2) Properties in the `common-properties` block are manually filled in each data point

In general, our philosophy is "explicit is better than implicit"; therefore, we chose the second scenario. We feel that the danger of someone forgetting to add a required value and having it implicitly filled from the `common-properties` with the wrong value is greater than the work required to add the property to each datapoint. Note, though, that even in the second scenario, the user is not required to type the value more than once, so we gain the advantages of reducing the risk of typos, while also forcing the user to think about what they're doing.

> Yeah, I'm not sure I even like the 'assumptions' field so much anyway

I can see one important use case, which is specifying constant pressure vs. constant volume, as you mention. There are also some butanol experiments that use what Ron's group calls CRV (constrained reactor volume, I think) that they model as constant p-h rather than the typical constant u-v. We do have a keyword for the pressure rise that's sometimes specified in the constant volume shock tube experiments. Maybe this could be a part of the `apparatus` block? `constant volume shock tube` vs. `crv shock tube` vs. `rcm` or something?

> In that case, does it still make sense to have 3 different YAML files to represent it?

We think the answer to this question is yes. Obviously there is some concern for typos, since there are a bunch of shared properties for the single experiment. I think the solution to this is to specify the common properties once and use a script to write multiple files. We're already sort of planning to have converter scripts from internal data formats to the standard format, so this would fit into that pretty neatly.

Another option that we've (I've) considered is putting a binary file encoded as a string into the data file, something like

    data: !!binary base64-string

See here also: http://yaml.org/type/binary.html This is something that Kyle and I haven't come to consensus on yet though.

> At different points along the time profile, the relative uncertainties may take on different values on an absolute basis.

If we can define how the relative uncertainty and absolute uncertainty combine, then that would be fine, I suppose, although I think my preference would be for the person writing the YAML file to just write out the absolute uncertainty for a single point in time.

> I should mention that the shock tube diameter is a necessary component to predicting the absorption signal through a Beer's Law analysis.

Yes, I think the diameter should be a required property if the absorbance is specified, except the diameter (really, path length, right, since there can be multiple reflections?) should be specified in each   data point, or in the common properties section and then referenced in each data point.
