### ISSUE TITLE
Which properties should be in common-properties?

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/PyKED#67]
At the moment, the `common-properties` section allows the following keys:

```
common-properties:
  type: dict
  schema:
    pressure: *value-unit-optional
    ignition-type: *ignition-type
    composition: *composition
    pressure-rise: *value-unit-optional
```

How can we handle the common properties without explicitly specifying which ones are allowed? I think that any property should be eligible to be a `common-property`.

**Comment by kyleniemeyer** [comment]
I agree that we should allow any property to be in `common-properties`

**Comment by kyleniemeyer** [comment]
I'm not sure the *easiest* way of doing this, but perhaps `common-properties:` in `chemked_schema.yaml` can be extended to:

```yaml
# Start the ChemKED schema
common-properties:
  type: dict
  schema:
    pressure: *value-unit-optional
    ignition-type: *ignition-type
    composition: *composition
    pressure-rise: *value-unit-optional
    compression-time: *value-unit-optional
    ignition-delay: *value-unit-required
    first-stage-ignition-delay: *value-unit-optional
    compressed-pressure: *value-unit-optional
    compressed-temperature: *value-unit-optional
    temperature: *value-unit-required
```
?

(Though I don't think we should really allow `ignition-delay` to be common...)
