### ISSUE TITLE
What happens if an optional field is included by blank?

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/PyKED#82]
### Code sample, preferably able to be copy-pasted and run with no changes
```
apparatus:
  kind: rapid compression machine
  institution:
  facility:
```

### Expected behavior
Guess we need to decide this

### Actual behavior, including any error messages
No idea :smile:
